<template>
    <div>
        <el-table
            :data="tableData"
            style="width: 100%">
            <el-table-column
                prop="date"
                label="游戏图片"
                width="180">
            </el-table-column>
            <el-table-column
                prop="name"
                label="游戏名称"
                width="180">
            </el-table-column>
            <el-table-column
                prop="address"
                label="副标题">
            </el-table-column>
            <el-table-column
                prop="address"
                label="游戏ID">
            </el-table-column>
            <el-table-column
                prop="address"
                label="游戏类型">
            </el-table-column>
            <el-table-column
                prop="address"
                label="游戏分类">
            </el-table-column>
            <el-table-column
                prop="address"
                label="上架时间">
            </el-table-column>
            <el-table-column
                prop="address"
                label="更新时间">
            </el-table-column>
            <el-table-column
                prop="address"
                label="状态">
            </el-table-column>
            <el-table-column
                prop="address"
                label="操作">
            </el-table-column>
        </el-table>
    </div>
</template>

<style></style>
